### ISSUE TITLE
Разобраться с неканоническим вводом на С под Windows

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#1]

**Comment by katherina-aidova** [comment]
для управления ввода и вывода в Linux предназначена библиотека ncursesподробнее о ее работе можно почитать здесь:http://linsovet.org.ua/ncurses-intro
PDCurses  использует те же вызовы, что и ncurses, за исключением того, что PDCurses предназначена для различных устройств, то есть, консольных окон DOS, Win32, OS/2 и X11.
https://sourceforge.net/projects/pdcurses/files/pdcurses/3.4/pdc34dll.zip/download

**Comment by katherina-aidova** [comment]
наверное из данной библиотеки самой полезной будет int keypad(WINDOW *win, bool bf)
 функция для обработки командных клавиш(функциональные и управления курсором)
Чтобы установить режим обработки командных клавиш нужно вызвать функцию keypad с TRUE в качестве второго параметра. Первый параметр указывает для какого окна Вы хотите установить данный режим. Если Вы не используете окна можно указать stdscr. Для отключения нужно передать FALSE во втором параметре.

**Comment by katherina-aidova** [comment]
Итак, подведем итоги работы над данным таском. Существует несколько путей решения данной задачи. 
- Самый простой, но нежелательный для нас, сменить платформу на Linux
- Воспользоваться возможностями  WinApi и перехватить прерывания для клавиатуры.Типичная оконная процедура игнорирует все сообщения о нажатии клавиши кроме WM_KEYDOWN. Windows посылает сообщение WM_KEYDOWN, когда пользователь нажимает клавишу.
  Когда оконная процедура принимает сообщение WM_KEYDOWN, она должна проверить код виртуальной клавиши, который сопровождает сообщение, чтобы установить, как обработать нажатие клавиши. Код виртуальной клавиши находится в параметре wParam сообщения.
  обработчик событий клавиатуры выглядит след образом:
  case WM_KEYDOWN:
  switch (wParam) {
      case VK_LEFT:
          /\* Обрабатывает клавишу LEFT ARROW (Стрелка влево). _/
      break
                      ....
                  /_ Обрабатывает другие не символьные нажатия клавиш. */
      default: 
      break;
  }
- Организовать посимвольное чтение с помощью функцией getch() для считывания очередного символа в консоли без вывода его на экран, далее с помощью оператора switch выбрать необходимое для символа действие.Кроме того getch() распознает нажатие специальных клавиш(tab, пробел, стрелки и т.д.)
