### ISSUE TITLE
Реализация интерпретатора командной строки с поддержкой передачи аргументов >, конструкций &&, ||

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#10]
https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D0%B9%D0%B5%D1%80_(UNIX)

**Comment by JuliaRS** [comment]
ОГРАНИЧЕНИЯ НА ИНТЕРПРЕТАТОР КОМАНДНОЙ СТРОКИ:
1) название команды (лишь буквы английского алфавита, регистр не важен)
2) через пробелы после названия команды следуют аргументы
3) "что-то вроде, но не pipe": разделитель ">"
4) В двойных кавычках может быть написан путь, содержащий пробелы
