### ISSUE TITLE
Реализация парсера аргументов

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#11]
Реализовать парсер строки аргументов, переводящий строку (`char*`) в список строк-аргументов (`STRLIST_NODE*`) по следующему правилу:
- если часть строки заключена в двойные кавычки ("), то эта подстрока считается одним аргументом
- все остальные слова (разделённые пробелами) - отдельные аргументы

Можно будет использовать его для облегчения написания программ, которые будут бить приходящую строку аргументов по такому стандартному правилу.

**Comment by akuporos** [comment]
- если перед кавычками отсутствует пробел, например spase"takes you", то space идет отдельным аргументом
- если количество кавычек нечетно, то выдает ошибку
