### ISSUE TITLE
Запись в реестр информации для "установки и удаления программ"

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#16]
Разобраться, какие нужно прописывать ключи в свой раздел в `HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\` чтобы информация об установке корректно воспринималась установкой и удалением программ.

**Comment by FionaRo** [comment]
| ИМЯ | ТИП | ЗНАЧЕНИЕ |
| --- | --- | --- |
| (По умолчанию) | REG_SZ | (значение не присвоено) |
| DisplayIcon | REG_SZ | C:\ |
| DisplayName | REG_SZ | NAME |
| InstallLocation | REG_SZ | C:\ |
| UninstallString | REG_SZ | C:\ |
| Publisher | REG_SZ | NAME |
| EstimatedSize | REG_DWORD | ? KB |
