### ISSUE TITLE
Разобраться с принципом работы интерпретатора языка и составить общую схему работы нашего

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#2]

**Comment by JuliaRS** [comment]
Разработка интерпретатора на с для подмножества языка с (little c):
http://cpp.com.ru/shildt_spr_po_c/VI.html
Опираемся пока на это, глава VI в этой книге посвящена этому

**Comment by kuppy28** [comment]
An interpreter generally uses one of the following strategies for program execution:

**1. parse the source code and perform its behavior directly.**  
2. translate source code into some efficient intermediate representation and immediately execute this.
3. explicitly execute stored precompiled code made by a compiler which is part of the interpreter system.

Пример интерпретатора языка си: https://habrahabr.ru/post/80141/

**Comment by JuliaRS** [comment]
ОГРАНИЧЕНИЯ НА ИНТЕРПРЕТАТОР КОМАНДНОЙ СТРОКИ:
1) название команды (лишь буквы английского алфавита, регистр не важен)
2) через пробелы после названия команды следуют аргументы
3) pipe: разделитель "|"

**Comment by JuliaRS** [comment]
Как задумка для интерпретатора языка(если останется время): 
1) "Паскалевкая модель"
описание переменных
    начало
          операторы
   конец
2) вся программа из одной функции состоит
3) без рекурсии
4) первым для реализации if, while, math operation
