### ISSUE TITLE
Написание математического интерпретатора для скриптового языка и программы-калькулятора

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#22]
Реализовать возвращающую int функцию (0 - ошибка, 1 - успех), принимающую:
- char\* - строка, которую нужно вычислить
- double\* - куда будет записан результат

Строка может содержать:
- целочисленные (для начала) константы
- скобки ( )
- пробелы (игнорировать)
- знаки операций \* / + -
- имена переменных

Для получения значения переменной реализовать возвращающую int функцию (0/1), принимающую:
- char\* - имя переменной
- long long\* (потом double*) - куда будет записан результат

На данном этапе это функция-заглушка, просто возвращать константу.

Реализовывать предлагаю на основании расширенной форма Бэкуса-Наура (статьи по теме думаю можно найти). Вкратце, это когда одни конструкции выражаются через другие и можно работать с выражением рекурсивно за один проход, постепенно передвигая указатель по строке.
### Пример
- [] - необязательные элементы
- | - или

Допустим у нас есть только +,-,*,скобки,целые константы,тогда
- Выражение = Слагаемое [+|- Выражение]
- Слагаемое = Множитель [\* Множитель]
- Множитель = Константа | Выражение

Для обработки каждого типа будет использоваться своя функция, которая будет рекурсивно вызывать другую, постепенно передвигая общий глобальный относительно них указатель на текущее положение в строке (т.е. не надо искать конец скобок при обнаружении открытой, это всё обработается позже само).

Код примера: http://pastebin.com/SYk8Vdwi

Первая задача до кода - понять что это за покемон и построить такую модель для нашего случая

Создать новый бранч под скриптовый язык, писать функцию там (потом переименуем бранч, когда придумаем название).
Функционал затем будет расширен, возможно потом подключим кого-нибудь ещё

**Comment by FionaRo** [comment]
{}-конкатенация любого числа элементов
- Число = НатЧисло [ " . " НатЧисло]
- Нат.Число = Цифра { Цифра }

Имеем +, -, *, /, скобки, вещественные константы, переменные, математические функции
- Выражение = Слагаемое [ + | - Выражение]
- Слагаемое = Множитель [ \* Слагаемое]
- Множитель = Константа | Переменная | Функция | Выражение
- Функция = МатФункция "( " Выражение ")"

деление - ?

**Comment by FionaRo** [comment]
Поддержка математических функций, функции strlen и конкатенации строк
Поддержка математических констант и строковых переменных
Поддержка функций от нескольких переменных: pow(a,b)
