### ISSUE TITLE
Встроенные программы. Общие правила.

### ISSUE THREAD

**Issue by JuliaRS** [15PI-Shell/Shell#24]
Builtin prodrams:
1) принимают char\* arg.
2) Вначале программы обязательна проверка на корректность пришедшего char \* arg (ВАЖНО).
3) возвращать тоже char\* arg. Arg - ссылается на результат, поэтому внутри программы иногда придётся делать arg = malloc(); ( при выделении памяти: количество символов в результате + одно места для '\0').

**Comment by Acuion** [comment]
Создание новой программы:

Каждая программа состоит из .h&.c файла расположенных в папках-фильтрах BuiltinPrograms.
Вызываемый интерпретатором обработчик принимает `char*`, возвращает `char*` (смотрите уже реализованные программы для примера)
- -1 в качестве возвращаемого значения означает что программа завершилась в ошибкой
- 0 - нечего возвращать
- любое другое значение - указатель на возвращаемый результат

Для регистрации программы (чтобы её стало возможно вызывать интерпретатору) необходимо подключить .h программы в BuiltinProgController.h и добавить строку в функцию BPC_Init в BuiltinProgController.c:
`RegisterProgram(`
- `"Имя программы, которое будет вызывать интерпретатор"`,
- `ФункцияОбработчикПрограммы`,
- Тип возвращаемого значения (будет применяться во встроенном языке для соблюдения строгой типизации)
  - `BPC_ReturnsInt` - в возвращаемой строке закодировано целочисленное значение
  - `BPC_ReturnsDouble` - вещественное
  - `BPC_ReturnsString` - строка
  - `BPC_ReturnsNothing` - ничего не возвращает (возвращает 0)

`);`
