### ISSUE TITLE
Запуск файла, ожидающий завершения и возвращающий код

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#27]
Можно просто 0 - Success, остальное - какой-нибудь BadReturnCode
В случае ошибки запуска возвращаем по enum что обычно

**Comment by FionaRo** [comment]
exe - запуск CreateProcess, ожидание завершение, возвращает 0 - удачно, остальное - ошибка
остальные файлы - запуск ShellExecute, 0 - удачный запуск, остальное ошибка. Ожидания завершения нет.
