### ISSUE TITLE
Разобраться с работой с системными переменными (PATH, ...)

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#3]

**Comment by FionaRo** [comment]
### Системные переменные. Командная строка.

 [список системных и локальных переменных windows](https://goo.gl/W2PgGu) (для нас по большей части имеет значение переменная `PATH`)
Переменные можно менять в командной строке (от администратора): 

> set NAME=VALUE

Если переменной с именем `NAME` ранее не существовало, то добавится новая переменная окружения.
Просто команда `set` выведет все переменные и их значения.
Path содержит пути поиска исполняемых файлов. По умолчанию там находятся некие пути, нужные определенному процессу (может глянуть`set PATH`). Для каждого процесса пути разные. Пути прописываются следующим образом:  `C:\...;C:\...` (через точку с запятой и начиная с `C:\`). Слеш в конце пути ничего не меняет (можно писать, можно не писать. Как хотите.). Все изменения отменяются после перезагрузки.
Чтобы не писать все пути по новой, делаем так:

>  set PATH=C:\progs;%PATH%

В этом случае в начале переменной PATH появится путь `C:\progs`. Аналогично можно добавить и в конец. 
Подробнее о команде о команде `set` смотрите [здесь](http://ab57.ru/cmdlist/set.html)

**Comment by FionaRo** [comment]
### Функции для работы с переменными окружения

На linux можно использовать несколько функций для работы с окружением. В этом нам помогает библиотека  `<unistd.h>`
Немного про окружение в целом и примеры кодов для работы с функциями можно посмотреть [здесь](https://www.opennet.ru/docs/RUS/zlp/004.html)
Си на windows так же поддерживает работу с окружением, но в меньшей степени, чем linux. 
В стандартной библиотеке `<stdlib.h>` лежит функция `getenv()`
Она выполняет поиск введенной пользователем переменной и возвращает указатель на значение этой переменной.
Функция и пример работы на windows описан [здесь](http://cppstudio.com/post/879/)

**Comment by FionaRo** [comment]
### Работа со значением переменной

Используя функцию `getenv()` мы получаем строку со значением переменной.
Её можно разбивать на отдельные пути (если говорить о `PATH`).
Этими путями можно пользоваться, чтобы открывать файлы из каталогов, перемещать их, удалять, добавлять новые, перезаписывать и т.д.
