### ISSUE TITLE
Понять как программно установить иконку (.ico файл) указанному .exe файлу

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#32]
1) http://www.vsokovikov.narod.ru/New_MSDN_API/Resourse/fn_beginupdateresource.htm
    HANDLE BeginUpdateResource(  
        LPCTSTR pFileName,
        BOOL bDeleteExistingResources
    );
Функция BeginUpdateResource возвращает дескриптор, который может использоваться функцией UpdateResource, которая добавляет, удаляет или заменяет ресурсы в исполняемом файле.
2) http://www.vsokovikov.narod.ru/New_MSDN_API/Resourse/fn_updateresource.htm
    BOOL UpdateResource(
        HANDLE hUpdate, (то что возвращает BeginUpdateResources)
        LPCTSTR lpType, (http://www.vsokovikov.narod.ru/New_MSDN_API/Other/res_types.htm)
        LPCTSTR lpName,
        WORD wLanguage,
        LPVOID lpData,
        DWORD cbData
    );
RT_GROUP_ICON
3) http://www.vsokovikov.narod.ru/New_MSDN_API/Resourse/fn_endupdateresource.htm
    BOOL EndUpdateResource(
        HANDLE hUpdate,
        BOOL fDiscard
    );
Функция EndUpdateResource заканчивает модернизацию ресурса в исполняемом файле.

**Comment by JuliaRS** [comment]
http://www.vsokovikov.narod.ru/New_MSDN_API/Icon/about_icons.htm
