### ISSUE TITLE
Понять как дополнять пользовательский ввод

### ISSUE THREAD

**Issue by Acuion** [15PI-Shell/Shell#5]

**Comment by katherina-aidova** [comment]
# База команд

Для начала нам понадобится дерево используемых команд, с узлами которого мы будем сравнивать введенные пользователем данные.т.е. создается словарь команд. Данные проверяются посимвольно, при этом необходимо учитывать, что буффер "нерезиновый" и что привводе пользователь может использовать специальные клавиши кроме буквенно-цифровых(из которых состоят имена адресатов) специальные. 

# Управление предиктивным вводом
- при одиночном нажатии tab скрипт дополняет введенную команду, при условии что существует лишь единственный вариант дополнения
- при двойном нажатии tab  показываются  все возможные варианты дополнения.

# Реализация автодополнения введенных команд.

После выбора пользователем  автодополнения неоконченный ввод пользователя затирается, на его месте вписывается нужный адресат с последующим вызовом обработчика данного адресата. Однако есть одна важная проблема в которой мы можем столкнуться: Пользователь теряет возможность редактирования автодописанной команды. 
НЕОБХОДИМО найти пути решения данной проблемы.
В данной ситуации, я думаю, на помощь могут прийти команды WinApi Функция удаления символа, на мой взгляд, может выглядеть так
- Получение дескриптора окна
- Определение координат удаляемого символа или подстроки символов(в случае если необходимо удалить последовательность символов)
- Помещаем на месте символа пробел с атрибутами окна
- В случае с подстрокой, передвигаемся влево, изменяя координату х
